=== alialperen/CBRT-XML/xmldata/cbrt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/cbrt" xmlns:cbrtns="http://www.example.org/cbrt">
	
	<xs:element name="cbrt" type="cbrtns:cbrtType" />

	<xs:complexType name="cbrtType">
		<xs:sequence>
			<xs:element name="Governor" type="cbrtns:GovernorType" minOccurs="1" maxOccurs="1" />
			<xs:element name="DeputyGovernor" type="cbrtns:DeputyGovernorType" minOccurs="1" maxOccurs="4" />
			<xs:element name="MPC_member" type="cbrtns:MPC_memberType" minOccurs="1" maxOccurs="6" />
			<xs:element name="BoardMember" type="cbrtns:BoardMemberType" minOccurs="1" maxOccurs="7" />
			<xs:element name="AuditCommunityMember" type="cbrtns:AuditComMemberType" minOccurs="1" maxOccurs="4" />
			<xs:element name="ExecCommunityMember" type="cbrtns:ExecComMemberType" minOccurs="1" maxOccurs="5" />
			<xs:element name="Client" type="cbrtns:ClientType" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="ShareHolder" type="cbrtns:ShareHolderType" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="Branch" type="cbrtns:BranchType" minOccurs="1" maxOccurs="unbounded" />
			<xs:element name="Employee" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:choice>
						<xs:element name="Contractual" type="cbrtns:ContractualEmployeeType" />
						<xs:element name="Regular" type="cbrtns:RegularEmployeeType" />
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PersonType">
		<xs:sequence>
			<xs:element name="FirstName" type="xs:string" maxOccurs="10" minOccurs="1" />
			<xs:element name="MiddleName" type="xs:string" maxOccurs="1" minOccurs="0" />
			<xs:element name="LastName" type="xs:string" maxOccurs="2" minOccurs="1" />
		</xs:sequence>
		<xs:attribute name="SSN" type="cbrtns:SSN_type" use="required" />
	</xs:complexType>

	<xs:complexType name="EmployeeType">
		<xs:complexContent>
			<xs:extension base="cbrtns:PersonType">
				<xs:sequence>
					<xs:element name="Title" type="cbrtns:TitleType" />
					<xs:element name="AssignmentDate" type="xs:date" />
				</xs:sequence>
				<xs:attribute name="EmployeeNumber" type="cbrtns:EmployeeNumberType" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="GovernorType">
		<xs:complexContent>
			<xs:extension base="cbrtns:EmployeeType">
				<xs:sequence>
					<xs:element name="Graduate" type="cbrtns:GovernorGraduateType" />
					<xs:element name="AssignmentCount" type="xs:positiveInteger" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DeputyGovernorType">
		<xs:complexContent>
			<xs:extension base="cbrtns:EmployeeType">
				<xs:sequence>
					<xs:element name="Graduate" type="cbrtns:GovernorGraduateType" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="MPC_memberType">
		<xs:complexContent>
			<xs:extension base="cbrtns:PersonType">
				<xs:sequence>
					<xs:element name="AssignmentDate" type="xs:date" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="BoardMemberType">
		<xs:complexContent>
			<xs:extension base="cbrtns:PersonType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AuditComMemberType">
		<xs:complexContent>
			<xs:extension base="cbrtns:EmployeeType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ExecComMemberType">
		<xs:complexContent>
			<xs:extension base="cbrtns:EmployeeType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ClientType">
		<xs:choice>
			<xs:element name="Person" type="cbrtns:PersonType" />
			<xs:element name="Company" type="cbrtns:CompanyType" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="ShareHolderType">
		<xs:choice>
			<xs:element name="A_type" type="cbrtns:CompanyType" />
			<xs:element name="B_type" type="cbrtns:CompanyType" />
			<xs:element name="C_type" type="cbrtns:CompanyType" />
			<xs:element name="D_type" type="cbrtns:PersonType" />
		</xs:choice>
	</xs:complexType>

	<xs:complexType name="BranchType">
		<xs:all>
			<xs:element name="branchName" type="xs:string" />
			<xs:element name="branchLocation" type="xs:string" />
			<xs:element name="employee" type="cbrtns:EmployeeType" />
			<xs:element name="telNo" type="cbrtns:TelNoType" />
			<xs:element name="address" type="xs:string" />
		</xs:all>
		<xs:attribute name="branchID" type="xs:string" use="required" />
	</xs:complexType>


	<xs:complexType name="ContractualEmployeeType">
		<xs:complexContent>
			<xs:extension base="cbrtns:EmployeeType">
				<xs:sequence>
					<xs:element name="ContractExpDate" type="xs:date" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="RegularEmployeeType">
		<xs:complexContent>
			<xs:extension base="cbrtns:EmployeeType">
				<xs:sequence>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="CompanyType">
		<xs:sequence>
			<xs:element name="CompanyName" type="xs:string" />
			<xs:element name="Country" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="GovernorGraduateType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Economics" />
			<xs:enumeration value="Econometrics" />
			<xs:enumeration value="Banking" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TitleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Mr." />
			<xs:enumeration value="Mrs." />
			<xs:enumeration value="Miss." />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="SSN_type">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{10}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EmployeeNumberType">
		<xs:restriction base="xs:positiveInteger">
			<xs:pattern value="[0-9]{5}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="EftCodeType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{4}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TelNoType">
		<xs:restriction base="xs:string">
			<xs:pattern value="(\+\d{1,2}\s)?\(?\d{4}\)?[\s.-]\d{3}[\s.-]\d{4}" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="CbrtObjectiveType">
		<xs:restriction base="xs:string">
			<xs:enumeration value=" To achieve and maintain price stability" />
		</xs:restriction>
	</xs:simpleType>

	<xs:attribute name="eftCode" type="cbrtns:EftCodeType" />
	<xs:attribute name="telNo" type="cbrtns:TelNoType" />
	<xs:attribute name="objective" type="cbrtns:CbrtObjectiveType" />

</xs:schema>

=== alialperen/CBRT-XML/xmldata/Clients.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Clients.xsl"?>
<cbrtns:cbrt xmlns:cbrtns="http://www.example.org/cbrt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cbrt cbrt.xsd ">
	<Governor EmployeeNumber="00001" SSN="0000000001">
		<FirstName>Murat</FirstName>
		<LastName>Çetinkaya</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-04-01</AssignmentDate>
		<Graduate>Economics</Graduate>
		<AssignmentCount>1</AssignmentCount>
	</Governor>
	<DeputyGovernor EmployeeNumber="00002" SSN="0000000002">
		<FirstName>Erkan</FirstName>
		<LastName>Kilimci</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<MPC_member SSN="0000000003">
		<FirstName>Abdullah</FirstName>
		<LastName>Yavaş</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<BoardMember SSN="0000000004">
		<FirstName>Ahmet Faruk</FirstName>
		<LastName>Aysan</LastName>
	</BoardMember>
	<AuditCommunityMember EmployeeNumber="00003" SSN="0000000005">
		<FirstName>Murat </FirstName>
		<LastName>Uysal</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-06-09</AssignmentDate>
	</AuditCommunityMember>
	<ExecCommunityMember EmployeeNumber="00004" SSN="0000000006">
		<FirstName>Emrah</FirstName>
		<LastName>Şener</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-08-02</AssignmentDate>
	</ExecCommunityMember>
	<Client>
		<Company>
			<CompanyName>Alternatif Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Arap Türk Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Bank of Tokyo-Mitsubishi UFJ Turkey A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Burgan Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Citibank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Denizbank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Deutsche Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Finans Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>HSBC A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>ING Bank A.Ş.</CompanyName>
			<Country>NE</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Odeabank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Rabobank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>T-Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Bank Mellat</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Habib Bank Limited</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Intesa Sanpaolo S.P.A</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>JP Morgan Chase Bank N.A.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Société Générale S.A.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>The Royal Bank of Scotland PLC.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Adabank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Akbank T.A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Aktif Bank</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Anadolubank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Fibabanka A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Birleşik Fon Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Şekerbank T.A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Tekstilbank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Turkish Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türk Ekonomi Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye Garanti Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye İş Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Yapı ve Kredi Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Albaraka Türk Katılım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Bank Asya A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Kuveyt Türk Katılım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye Finans Katılım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>  Türkiye Cumhuriyeti Ziraat Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye Halk Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye Vakıflar Bankası T.A.O.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>BankPozitif Kredi ve Kalkınma Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Merrill Lynch Yatırım Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Standard Chartered Yatırım Bankası Türk A.Ş</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Aktif Yatırım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Diler Yatırım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>GSD Yatırım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>İstanbul Takas ve Saklama Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Nurol Yatırım Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Taib Yatırım Bank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye Sınai Kalkınma Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>İller Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türk Eximbank A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>
	<Client>
		<Company>
			<CompanyName>Türkiye Kalkınma Bankası A.Ş.</CompanyName>
			<Country>TR</Country>
		</Company>
	</Client>

	<ShareHolder>
		<A_type>
			<CompanyName>Treasury</CompanyName>
			<Country>TR</Country>
		</A_type>
	</ShareHolder>
	<Branch branchID="2">
		<branchLocation>Ankara</branchLocation>
		<branchName>Ankara Şubesi</branchName>
		<telNo>(0312) 507 7301</telNo>
		<address>Atatürk Bulvarı No:4 06100 Ulus Ankara</address>
		<employee EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Yusuf</FirstName>
			<LastName>Enhoş</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
		</employee>
	</Branch>
	<Employee>
		<Contractual EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Ali</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
</cbrtns:cbrt>

=== alialperen/CBRT-XML/xmldata/ShareHolders.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ShareHolders.xsl"?>
<cbrtns:cbrt xmlns:cbrtns="http://www.example.org/cbrt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cbrt cbrt.xsd ">
	<Governor EmployeeNumber="00001" SSN="0000000001">
		<FirstName>Murat</FirstName>
		<LastName>Çetinkaya</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-04-01</AssignmentDate>
		<Graduate>Economics</Graduate>
		<AssignmentCount>1</AssignmentCount>
	</Governor>
	<DeputyGovernor EmployeeNumber="00002" SSN="0000000002">
		<FirstName>Erkan</FirstName>
		<LastName>Kilimci</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<MPC_member SSN="0000000003">
		<FirstName>Abdullah</FirstName>
		<LastName>Yavaş</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<BoardMember SSN="0000000004">
		<FirstName>Ahmet Faruk</FirstName>
		<LastName>Aysan</LastName>
	</BoardMember>
	<AuditCommunityMember EmployeeNumber="00003" SSN="0000000005">
		<FirstName>Murat </FirstName>
		<LastName>Uysal</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-06-09</AssignmentDate>
	</AuditCommunityMember>
	<ExecCommunityMember EmployeeNumber="00004" SSN="0000000006">
		<FirstName>Emrah</FirstName>
		<LastName>Şener</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-08-02</AssignmentDate>
	</ExecCommunityMember>
	<Client>
		<Person SSN="0000000007">
			<FirstName>Mehmet</FirstName>
			<LastName>Yılmaz</LastName>
		</Person>
	</Client>
	<ShareHolder>
		<A_type>
			<CompanyName>Hazine</CompanyName>
			<Country>TR</Country>
		</A_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>TCMB Mensupları Sosyal Güvenlik ve Yardımlaşma Sandığı Vakfı</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>T.C. Ziraat Bankası</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Türkiye Garanti Bankası</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Türkiye İş Bankası</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Türkiye Halk Bankası</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Yapı Kredi Bankası</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Akbank</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Türkiye Ekonomi Bankası (TEB)</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>T.C. Sosyal Güvenlik Kurumu</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<B_type>
			<CompanyName>Türkiye Kızılay Derneği</CompanyName>
			<Country>TR</Country>
		</B_type>
	</ShareHolder>
	<ShareHolder>
		<C_type>
			<CompanyName>ING Bank</CompanyName>
			<Country>NE</Country>
		</C_type>
	</ShareHolder>
	<ShareHolder>
		<D_type SSN="0000000099">
			<FirstName>Adnan</FirstName>
			<LastName>Aktar</LastName>
		</D_type>
	</ShareHolder>
	<Branch branchID="2">
		<branchLocation>Ankara</branchLocation>
		<branchName>Ankara Şubesi</branchName>
		<telNo>(0312) 507 7301</telNo>
		<address>Atatürk Bulvarı No:4 06100 Ulus Ankara</address>
		<employee EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Yusuf</FirstName>
			<LastName>Enhoş</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
		</employee>
	</Branch>
	<Employee>
		<Contractual EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Ali</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
</cbrtns:cbrt>

=== alialperen/CBRT-XML/xmldata/Management.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Management.xsl"?>
<cbrtns:cbrt xmlns:cbrtns="http://www.example.org/cbrt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cbrt cbrt.xsd ">
	<Governor EmployeeNumber="00001" SSN="0000000001">
		<FirstName>Murat</FirstName>
		<LastName>Çetinkaya</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-04-01</AssignmentDate>
		<Graduate>Economics</Graduate>
		<AssignmentCount>1</AssignmentCount>
	</Governor>
	<DeputyGovernor EmployeeNumber="00010" SSN="0000000010">
		<FirstName>Erkan</FirstName>
		<LastName>Kilimci</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<DeputyGovernor EmployeeNumber="00011" SSN="0000000011">
		<FirstName>Erhan</FirstName>
		<LastName>Halıcı</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<DeputyGovernor EmployeeNumber="00012" SSN="0000000012">
		<FirstName>Erman</FirstName>
		<LastName>Bademci</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<DeputyGovernor EmployeeNumber="00013" SSN="0000000013">
		<FirstName>Ertan</FirstName>
		<LastName>Fıstıkçı</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<MPC_member SSN="0000000073">
		<FirstName>Abdullah</FirstName>
		<LastName>Yavaş</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<MPC_member SSN="0000000023">
		<FirstName>Abdurrahman</FirstName>
		<LastName>Hızlı</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<MPC_member SSN="0000000033">
		<FirstName>Abdurahim</FirstName>
		<LastName>Durgun</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<MPC_member SSN="0000000043">
		<FirstName>Abdussamet</FirstName>
		<LastName>Canıtez</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<MPC_member SSN="0000000053">
		<FirstName>Abdulkadir</FirstName>
		<LastName>Sakin</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<MPC_member SSN="0000000063">
		<FirstName>Abdulhamit</FirstName>
		<LastName>Çevik</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<BoardMember SSN="0000000004">
		<FirstName>Ahmet Faruk</FirstName>
		<LastName>Aysan</LastName>
	</BoardMember>
	<BoardMember SSN="0000000014">
		<FirstName>Vehbi</FirstName>
		<LastName>Çıtak</LastName>
	</BoardMember>
	<BoardMember SSN="0000000024">
		<FirstName>Lokman</FirstName>
		<LastName>Gündüz</LastName>
	</BoardMember>
	<BoardMember SSN="0000000034">
		<FirstName>Necdet</FirstName>
		<LastName>Şensoy</LastName>
	</BoardMember>
	<BoardMember SSN="0000000044">
		<FirstName>Sabri</FirstName>
		<LastName>Orman</LastName>
	</BoardMember>
	<BoardMember SSN="0000000054">
		<FirstName>Nurullah</FirstName>
		<LastName>Genç</LastName>
	</BoardMember>
	<AuditCommunityMember EmployeeNumber="00003" SSN="0000000005">
		<FirstName>Murat </FirstName>
		<LastName>Uysal</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-06-09</AssignmentDate>
	</AuditCommunityMember>
	<ExecCommunityMember EmployeeNumber="00004" SSN="0000000006">
		<FirstName>Emrah</FirstName>
		<LastName>Şener</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-08-02</AssignmentDate>
	</ExecCommunityMember>
	<Client>
		<Person SSN="0000000007">
			<FirstName>Mehmet</FirstName>
			<LastName>Yılmaz</LastName>
		</Person>
	</Client>
	<ShareHolder>
		<A_type>
			<CompanyName>Treasury</CompanyName>
			<Country>TR</Country>
		</A_type>
	</ShareHolder>
	<Branch branchID="2">
		<branchLocation>Ankara</branchLocation>
		<branchName>Ankara Şubesi</branchName>
		<telNo>(0312) 507 7301</telNo>
		<address>Atatürk Bulvarı No:4 06100 Ulus Ankara</address>
		<employee EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Yusuf</FirstName>
			<LastName>Enhoş</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
		</employee>
	</Branch>
	<Employee>
		<Contractual EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Ali</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
</cbrtns:cbrt>

=== alialperen/CBRT-XML/xmldata/Employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Employees.xsl"?>
<cbrtns:cbrt xmlns:cbrtns="http://www.example.org/cbrt" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/cbrt cbrt.xsd ">
	<Governor EmployeeNumber="00001" SSN="0000000001">
		<FirstName>Murat</FirstName>
		<LastName>Çetinkaya</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-04-01</AssignmentDate>
		<Graduate>Economics</Graduate>
		<AssignmentCount>1</AssignmentCount>
	</Governor>
	<DeputyGovernor EmployeeNumber="00002" SSN="0000000002">
		<FirstName>Erkan</FirstName>
		<LastName>Kilimci</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-05-16</AssignmentDate>
		<Graduate>Economics</Graduate>
	</DeputyGovernor>
	<MPC_member SSN="0000000003">
		<FirstName>Abdullah</FirstName>
		<LastName>Yavaş</LastName>
		<AssignmentDate>2008-03-11</AssignmentDate>
	</MPC_member>
	<BoardMember SSN="0000000004">
		<FirstName>Ahmet Faruk</FirstName>
		<LastName>Aysan</LastName>
	</BoardMember>
	<AuditCommunityMember EmployeeNumber="00003" SSN="0000000005">
		<FirstName>Murat </FirstName>
		<LastName>Uysal</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-06-09</AssignmentDate>
	</AuditCommunityMember>
	<ExecCommunityMember EmployeeNumber="00004" SSN="0000000006">
		<FirstName>Emrah</FirstName>
		<LastName>Şener</LastName>
		<Title>Mr.</Title>
		<AssignmentDate>2016-08-02</AssignmentDate>
	</ExecCommunityMember>
	<Client>
		<Person SSN="0000000007">
			<FirstName>Mehmet</FirstName>
			<LastName>Yılmaz</LastName>
		</Person>
	</Client>
	<ShareHolder>
		<A_type>
			<CompanyName>Treasury</CompanyName>
			<Country>TR</Country>
		</A_type>
	</ShareHolder>
	<Branch branchID="2">
		<branchLocation>Ankara</branchLocation>
		<branchName>Ankara Şubesi</branchName>
		<telNo>(0312) 507 7301</telNo>
		<address>Atatürk Bulvarı No:4 06100 Ulus Ankara</address>
		<employee EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Yusuf</FirstName>
			<LastName>Enhoş</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
		</employee>
	</Branch>
	<Employee>
		<Contractual EmployeeNumber="00006" SSN="0000000009">
			<FirstName>Ahmet</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
	<Employee>
		<Contractual EmployeeNumber="00016" SSN="0000000169">
			<FirstName>Mehmet</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
	<Employee>
		<Contractual EmployeeNumber="00006" SSN="0000000069">
			<FirstName>Ali</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
	<Employee>
		<Contractual EmployeeNumber="00007" SSN="0000000079">
			<FirstName>Veli</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mr.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>
	<Employee>
		<Contractual EmployeeNumber="00008" SSN="0000000089">
			<FirstName>Ayşe</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mrs.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>

	<Employee>
		<Contractual EmployeeNumber="00009" SSN="0000000099">
			<FirstName>Fatma</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mrs.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
			<ContractExpDate>2016-12-31</ContractExpDate>
		</Contractual>
	</Employee>

	<Employee>
		<Regular EmployeeNumber="00109" SSN="0000000199">
			<FirstName>Hatice</FirstName>
			<LastName>Korkmaz</LastName>
			<Title>Mrs.</Title>
			<AssignmentDate>2001-01-01</AssignmentDate>
		</Regular>
	</Employee>
</cbrtns:cbrt>
